### ISSUE TITLE
How to load settings from services-config.xml 

### ISSUE THREAD

**Issue by bmontalvoDD** [SolidSoft-Lda/AMFCore#2]
I'd like to override the default AMFDestination without modifying your original code. I noticed there's references to a services-config.xml but I'm having difficulty figuring out the structure of that file as well as how to tell the code to load it. From what I'm seeing in the code, it doesn't appear this loading logic is ever used, can you please clarify? Thank you so much!

**Comment by SolidSoft-Lda** [comment]
Sorry for the late reply.
Yes, it's never used.
If you really need it, you can improve and pull a request to merge.
